config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: { sign_in: 'admin', sign_out: 'logout' }

  root 'home#index'

  get 'contact',   to: 'contact#index',     as: :contact
  match 'contact', to: 'contact#send_mail', as: :submit_contact_form, via: :post

  get 'about', to: 'about#index', as: :about

  resources :settings, only: %i(index show edit update)

  resources :page_element_texts, path: 'page-element-texts', only: %i(edit show update)
  resources :page_element_links, path: 'page-element-links', only: %i(edit show update)

  # Services
  resources :services, only: %i(index show edit update) do
    resources :questions
  end

  get 'services/:service_id/questions', to: 'questions#index', as: :questions

  get 'services/:id/images',                            to: 'service_images#index',   as: :service_images
  get 'services/:id/images/new',                        to: 'service_images#new',     as: :new_service_image
  get 'services/:service_id/images/:image_id/edit',     to: 'service_images#edit',    as: :edit_service_image
  match 'services/:service_id/images/:image_id',        to: 'service_images#update',  via: :patch
  match 'services/:id/images',                          to: 'service_images#create',  as: :create_service_image, via: :post
  match 'services/:service_id/images/:image_id/delete', to: 'service_images#destroy', as: :delete_service_image, via: :delete

  get 'redirect-locale/fr', to: 'home#chose_fr_locale', as: :fr_locale_redirect
  get 'redirect-locale/en', to: 'home#chose_en_locale', as: :en_locale_redirect
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :questions,      dependent: :destroy
  has_many :service_images, dependent: :destroy

  validates :title_en, presence: true
  validates :title_fr, presence: true

  def to_param
    [id, self["title_#{I18n.locale}"].parameterize].join('-')
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!, except: %w( index show )

  def index
    redirect_to Service.first
  end

  def show
    @services = Service.all.order(:order)
    @service = Service.find(params[:id])
    @page_title = @service["title_#{I18n.locale}"]
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                        autolink: true,
                                        space_after_headers: true,
                                        fenced_code_blocks: true,
                                        prettify: true)
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])

    if @service.update_attributes(service_params)
      flash[:success] = 'Service updated'
      redirect_to service_path @service
    else
      render :edit
    end
  end

  private

    def service_params
      params.require(:service).permit(:title_en, :title_fr, :body_en, :body_fr,
                                      :short_info_en, :short_info_fr,
                                      :font_class, :order)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_sidebar_list.html.erb
<ul class="services-sidebar-list">
    <% @services.each do |service| %>
        <li class="<% if service_url(service) == request.original_url %>m-active<% end %>">
            <i class="<%= service.font_class %>"></i>
            <%= link_to service["title_#{I18n.locale}"], service %>
        </li>
    <% end %>
</ul>

app/views/services/edit.html.erb
<div class="container settings-container">
  <%= form_for @service, html: { class: 'form-horizontal' } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <%= f.label :title_en, 'Title (English)', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title_en, auto_focus: true, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :title_fr, 'Title (French)', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title_fr, auto_focus: true, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :short_info_en, 'Short Info (English)', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :short_info_en, rows: 3, class: 'form-control' %>
        <span class="help-block">Text that is shown when you hover over the service on the home page.</span>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :short_info_fr, 'Short Info (French)', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :short_info_fr, rows: 3, class: 'form-control' %>
        <span class="help-block">Text that is shown when you hover over the service on the home page.</span>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :body_en, 'Body (English)', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :body_en, rows: 15, class: 'form-control', id: 'editor' %>
        <span class="help-block">
          <%= link_to 'Learn how to style text.', '#', class: 'learn-markdown', 'data-toggle' => 'modal', 'data-target' => '#learn_markdown' %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :body_fr, 'Body (French)', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :body_fr, rows: 15, class: 'form-control', id: 'editor_2' %>
        <span class="help-block">
          <%= link_to 'Learn how to style text.', '#', class: 'learn-markdown', 'data-toggle' => 'modal', 'data-target' => '#learn_markdown' %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :font_class, 'Font Class (don\'t touch)', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :font_class, class: 'form-control' %>
        <span class="help-block">Do not touch, let Tim change this.</span>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :order, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :order, class: 'form-control' %>
        <span class="help-block">The order in which the services are displayed everywhere.</span>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Update', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/services/show.html.erb
<!-- PAGE TITLE : begin -->
<div id="page-title" class="m-parallax">

  <!-- PAGE TITLE TOP : begin -->
  <div class="page-title-top">
    <div class="page-title-top-inner">

      <!-- PAGE TITLE TEXT : begin -->
      <div class="page-title-text">
        <div class="container">
          <h1><%= @service["title_#{I18n.locale}"] %></h1>
        </div>
      </div>
      <!-- PAGE TITLE TEXT : end -->

    </div>
  </div>
  <!-- PAGE TITLE TOP : end -->

  <!-- PAGE TITLE BOTTOM : begin -->
  <div class="page-title-bottom">
    <div class="container">
      <div class="page-title-bottom-inner">
        <div class="page-title-bottom-inner2">

          <!-- PAGE TITLE BREADCRUMBS : begin -->
          <div class="page-title-breadcrumbs">
            <ul>
              <li><%= link_to t('general.home'), root_path %></li>
              <li><%= @service["title_#{I18n.locale}"] %></li>
            </ul>
          </div>
          <!-- PAGE TITLE BREADCRUMBS : end -->

        </div>
      </div>
    </div>
  </div>
  <!-- PAGE TITLE BOTTOM : end -->

</div>
<!-- PAGE TITLE : end -->

<div class="container">
  <div class="row">
    <% if user_signed_in? %>
      <div class="pull-left action-bar">
        <%= link_to 'Edit Service', edit_service_path(@service), class: 'btn btn-default' %>
      </div>
    <% end %>

    <div class="col-md-9 col-md-push-3">

      <!-- PAGE CONTENT : begin -->
      <div id="page-content">

        <h2><%= @service["title_#{I18n.locale}"] %></h2>

        <div class="row">
          <div class="col-md-12">
            <%= @markdown.render(@service["body_#{I18n.locale}"]).html_safe %>
          </div>
        </div>

        <hr class="c-divider m-size-small m-transparent">

        <!-- ACCORDION : begin -->
        <ul class="c-accordion">

          <!-- PRICING : begin -->
          <li>
            <h4 class="accordion-title"><i class="im im-cash"></i><%= t('services.pricing') %></h4>
            <div class="accordion-content">
              <p class="center">
                <%= edit_text("service_#{@service.id}_pricing", 'I prefer to quote jobs individually. To get a free, no obligation quote [get in touch](/contact).', p_tags: false) %>
              </p>
            </div>
          </li>
          <!-- PRICING : end -->

          <% if @service.service_images.any? || user_signed_in? %>
            <!-- GALLERY : begin -->
            <li>
              <h4 class="accordion-title"><i class="im im-photo"></i><%= t('services.gallery') %></h4>
              <div class="accordion-content">

                <div class="c-gallery m-4-per-row">
                  <% if @service.service_images.any? %>
                    <ul>
                      <% @service.service_images.each do |image| %>
                        <li>
                          <%= link_to image.image.url, class: 'lightbox', title: image.alt_text do %>
                            <%= image_tag image.image.url, alt: image.alt_text %>
                          <% end %>

                          <% if user_signed_in? %>
                            <%= link_to delete_service_image_path(@service, image), class: 'text-danger', method: :delete, data: { confirm: 'Are you sure?' } do %>
                              <i class="fa fa-times"></i>
                              Delete
                            <% end %>
                          <% end %>
                        </li>
                      <% end %>
                    </ul>
                    <% if user_signed_in? %>
                      <p class="center serice-add-more">
                        <%= link_to new_service_image_path(@service), class: 'btn btn-default' do %>
                          <i class="fa fa-plus"></i>
                          Add Image
                        <% end %>
                      </p>
                    <% end %>
                  <% else %>
                    <p class="center">
                      There are no images for this service
                      <%= link_to 'add one here.', new_service_image_path(@service) %>
                    </p>
                  <% end %>
                </div>

              </div>
            </li>
            <!-- GALLERY : end -->
          <% end %>

          <% if user_signed_in? || @service.questions.any? %>
            <!-- FAQ : begin -->
            <li>
              <h4 class="accordion-title"><i class="im im-question"></i><%= t('services.faq') %></h4>
              <div class="accordion-content">
                <% if @service.questions.any? %>
                  <dl>
                    <% @service.questions.each do |question| %>
                      <dt>
                        <% if user_signed_in? %>
                          <div class="pull-right">
                            <%= link_to 'Edit', edit_service_question_path(@service, question), class: 'btn btn-default' %>
                            <%= link_to 'Delete', service_question_path(@service, question), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
                          </div>
                        <% end %>
                        <%= question["question_#{I18n.locale}"] %>
                      </dt>
                      <dd><%= question["answer_#{I18n.locale}"] %></dd>
                    <% end %>
                    <% if user_signed_in? %>
                      <p class="center serice-add-more">
                        <%= link_to new_service_question_path(@service), class: 'btn btn-default' do %>
                          <i class="fa fa-plus"></i>
                          Add Question
                        <% end %>
                      </p>
                    <% end %>
                  </dl>
                <% else %>
                  <p class="center">
                    There are no FAQs for this service
                    <%= link_to 'add one here.', new_service_question_path(@service) %>
                  </p>
                <% end %>
              </div>
            </li>
            <!-- FAQ : end -->
          <% end %>

        </ul>
        <!-- ACCORDION : end -->

      </div>
      <!-- PAGE CONTENT : end -->

    </div>
    <div class="col-md-3 col-md-pull-9">

      <hr class="c-divider m-size-large m-type-2 hidden-lg hidden-md">

      <!-- SIDEBAR : begin -->
      <div id="sidebar">
        <div class="sidebar-widget-list">

          <!-- SERVICES WIDGET : begin -->
          <div class="widget services-widget">
            <div class="widget-inner">
              <h3 class="widget-title"><%= t('nav.services') %></h3>
              <%= render 'services/sidebar_list' %>
            </div>
          </div>
          <!-- SERVICES WIDGET : end -->

        </div>
      </div>
      <!-- SIDEBAR : end -->

    </div>
  </div>
</div>