config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: { sign_in: 'admin', sign_out: 'logout' }

  root 'home#index'

  get 'contact',   to: 'contact#index',     as: :contact
  match 'contact', to: 'contact#send_mail', as: :submit_contact_form, via: :post

  get 'about', to: 'about#index', as: :about

  resources :settings, only: %i(index show edit update)

  resources :page_element_texts, path: 'page-element-texts', only: %i(edit show update)
  resources :page_element_links, path: 'page-element-links', only: %i(edit show update)

  # Services
  resources :services, only: %i(index show edit update) do
    resources :questions
  end

  get 'services/:service_id/questions', to: 'questions#index', as: :questions

  get 'services/:id/images',                            to: 'service_images#index',   as: :service_images
  get 'services/:id/images/new',                        to: 'service_images#new',     as: :new_service_image
  get 'services/:service_id/images/:image_id/edit',     to: 'service_images#edit',    as: :edit_service_image
  match 'services/:service_id/images/:image_id',        to: 'service_images#update',  via: :patch
  match 'services/:id/images',                          to: 'service_images#create',  as: :create_service_image, via: :post
  match 'services/:service_id/images/:image_id/delete', to: 'service_images#destroy', as: :delete_service_image, via: :delete

  get 'redirect-locale/fr', to: 'home#chose_fr_locale', as: :fr_locale_redirect
  get 'redirect-locale/en', to: 'home#chose_en_locale', as: :en_locale_redirect
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validates :key,         presence: true
  validates :value,       presence: true
  validates :pretty_name, presence: true
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @settings = Setting.all.order('pretty_name asc')
  end

  def edit
    @setting = Setting.find(params[:id])
  end

  def update
    @setting = Setting.find(params[:id])

    if @setting.update_attributes(setting_params)
      flash[:success] = 'Setting updated'
      redirect_to settings_path
    else
      render :edit
    end
  end

  private

    def setting_params
      params.require(:setting).permit(:value)
    end
end

app/views/settings/edit.html.erb
<div class="container settings-container">
  <%= form_for @setting, html: { class: 'form-horizontal' } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <label class="col-sm-2 control-label">Key</label>
      <div class="col-sm-10">
        <p class="form-control-static"><%= @setting.pretty_name %></p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :value, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :value, auto_focus: true, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Update', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/settings/index.html.erb
<div class="container settings-container">
  <% if @settings.any? %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @settings.each do |setting| %>
          <tr>
            <td><%= setting.pretty_name %></td>
            <td><%= setting.value %></td>
            <td>
              <%= link_to 'Edit', edit_setting_path(setting) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h3 class="center">There are no settings to display.</p>
  <% end %>
</div>